# Change these first
owner: securezeron # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: ASM
    url: https://devapi.cogz.one/billing/v1/plans/
    icon: https://static.zeron.cloud/v1/images/attack_surface.svg
  - name: Business Posture
    url: https://en.wikipedia.org
    icon: https://static.zeron.cloud/v1/images/business_posture.svg
  - name: Compliance
    url: https://news.ycombinator.com
    icon: https://static.zeron.cloud/v1/images/compliance.svg
  - name: Integrations
    url: https://news.ycombinator.com
    icon: https://static.zeron.cloud/v1/images/integration.svg
  - name: Cloud Monitor
    url: https://news.ycombinator.com
    icon: https://static.zeron.cloud/v1/images/cloud_monitoring.svg
  - name: VRM
    url: https://www.google.com
    icon: https://static.zeron.cloud/v1/images/vrm.svg
    assignees:
      - waris-zeron

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"      

incidents:
  - name: "Database Outage"
    description: "We experienced a database outage that affected several services."
    start_time: "2023-07-25T12:00:00Z"
    end_time: "2023-07-25T13:30:00Z"
    severity: "high"
    affected_components:
      - "Database"
      - "API"
  - name: "Network Latency"
    description: "Increased network latency was observed affecting user access."
    start_time: "2023-08-15T08:00:00Z"
    end_time: "2023-08-15T09:00:00Z"
    severity: "medium"
    affected_components:
      - "Network"
      - "Web Server"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  # favicon: 
  themeUrl: https://securezeron.github.io/uptime/my-custom-theme.css
  # logoUrl: https://zeron.one/wp-content/uploads/2023/09/white-logo-resized-108x21-1.png
  name: Zeron Status
  logoUrl: https://static.zeron.cloud/v1/images/favicon_final.svg
  introTitle: "**Zeron - Cyber Risk Posture Management Platform**"
  introMessage: Zeron Service Status
  navbar:
    - title: Status
      href: /uptime/

i18n:
  footer: Zeron      
